package protocol

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"net"
	"net/http"
	"strings"
	"time"

	"github.com/gorilla/websocket"
	"k8s.io/klog/v2"

	"github.com/knwgo/yarp/stat"
)

var wsUpgrader = websocket.Upgrader{
	ReadBufferSize:  8192,
	WriteBufferSize: 8192,
	CheckOrigin: func(r *http.Request) bool {
		return true
	},
}

func isWebSocketRequest(header []byte) bool {
	lower := bytes.ToLower(header)
	hasUpgrade := bytes.Contains(lower, []byte("upgrade: websocket"))
	hasConnection := bytes.Contains(lower, []byte("connection: upgrade"))
	return hasUpgrade && hasConnection
}

func handleWsConnection(clientConn net.Conn, targetHost string, ruleKey string) {
	// Read the HTTP request from client
	bc := newBufConn(clientConn, 8192)
	headerBuf, err := readHTTPHeaders(bc)
	if err != nil {
		klog.Errorf("read http headers error: %v", err)
		_ = clientConn.Close()
		return
	}

	// Parse the HTTP request
	req, err := http.ReadRequest(bufio.NewReader(bytes.NewReader(headerBuf)))
	if err != nil {
		klog.Errorf("parse http request error: %v", err)
		_ = clientConn.Close()
		return
	}

	// Get the path for dialing target
	path := req.URL.Path
	if req.URL.RawQuery != "" {
		path = path + "?" + req.URL.RawQuery
	}

	// Filter out WebSocket headers that will be auto-generated by Dial
	filteredHeader := http.Header{}
	for k, v := range req.Header {
		lowerK := strings.ToLower(k)
		if lowerK != "sec-websocket-key" &&
			lowerK != "sec-websocket-accept" &&
			lowerK != "sec-websocket-version" &&
			lowerK != "sec-websocket-extensions" &&
			lowerK != "sec-websocket-protocol" &&
			lowerK != "connection" &&
			lowerK != "upgrade" {
			filteredHeader[k] = v
		}
	}
	filteredHeader.Set("X-Forwarded-For", clientConn.RemoteAddr().String())

	// Dial to target as WebSocket client
	wsTarget, _, err := websocket.DefaultDialer.Dial(
		"ws://"+targetHost+path,
		filteredHeader,
	)
	if err != nil {
		klog.Errorf("dial target websocket error: %v", err)
		_ = clientConn.Close()
		return
	}
	defer wsTarget.Close()

	// Upgrade client connection to WebSocket
	wsClient, err := wsUpgrader.Upgrade(&responseWriter{conn: clientConn}, req, nil)
	if err != nil {
		klog.Errorf("upgrade client connection error: %v", err)
		_ = clientConn.Close()
		return
	}
	defer wsClient.Close()

	// Start statistics tracking
	stat.GlobalStats.AddConn(ruleKey)
	defer stat.GlobalStats.RemoveConn(ruleKey)

	klog.Infof("[ws] new connection: %s -> %s", clientConn.RemoteAddr(), targetHost)

	// Bidirectional copy with stats
	done := make(chan struct{})

	go func() {
		defer func() {
			wsClient.Close()
			wsTarget.Close()
			close(done)
		}()

		for {
			mt, msg, err := wsClient.ReadMessage()
			if err != nil {
				break
			}
			err = wsTarget.WriteMessage(mt, msg)
			if err != nil {
				break
			}
			stat.GlobalStats.AddBytes(ruleKey, 0, int64(len(msg)))
		}
	}()

	go func() {
		defer func() {
			wsClient.Close()
			wsTarget.Close()
		}()

		for {
			mt, msg, err := wsTarget.ReadMessage()
			if err != nil {
				break
			}
			err = wsClient.WriteMessage(mt, msg)
			if err != nil {
				break
			}
			stat.GlobalStats.AddBytes(ruleKey, int64(len(msg)), 0)
		}
	}()

	<-done
}

// responseWriter wraps net.Conn to implement http.ResponseWriter and http.Hijacker
type responseWriter struct {
	conn net.Conn
}

func (rw *responseWriter) Header() http.Header {
	return make(http.Header)
}

func (rw *responseWriter) WriteHeader(statusCode int) {
	// Write HTTP response status
	buf := fmt.Sprintf("HTTP/1.1 %d %s\r\n", statusCode, http.StatusText(statusCode))
	_, _ = rw.conn.Write([]byte(buf))
}

func (rw *responseWriter) Write(data []byte) (int, error) {
	return rw.conn.Write(data)
}

func (rw *responseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	return rw.conn, bufio.NewReadWriter(bufio.NewReader(rw.conn), bufio.NewWriter(rw.conn)), nil
}

func readHTTPHeaders(conn *bufConn) ([]byte, error) {
	_ = conn.SetReadDeadline(time.Now().Add(3 * time.Second))
	defer func() {
		_ = conn.SetReadDeadline(time.Time{})
	}()

	var headerBuf bytes.Buffer
	tmp := make([]byte, 1024)

	for {
		n, err := conn.Read(tmp)
		if n > 0 {
			headerBuf.Write(tmp[:n])
			if bytes.Contains(headerBuf.Bytes(), []byte("\r\n\r\n")) {
				break
			}
		}

		if err != nil {
			if err == io.EOF && headerBuf.Len() > 0 {
				break
			}
			return nil, err
		}

		if headerBuf.Len() > 128*1024 {
			return nil, fmt.Errorf("header too large")
		}
	}

	return headerBuf.Bytes(), nil
}

func parseWebSocketHost(b []byte) string {
	lines := bytes.Split(b, []byte("\r\n"))
	for _, line := range lines {
		l := bytes.ToLower(line)
		if bytes.HasPrefix(l, []byte("host:")) {
			host := bytes.TrimSpace(line[len("host:"):])
			return string(host)
		}
	}
	return ""
}

func getWebSocketPath(b []byte) string {
	lines := bytes.Split(b, []byte("\r\n"))
	for _, line := range lines {
		if bytes.HasPrefix(line, []byte("GET")) {
			parts := bytes.Split(line, []byte(" "))
			if len(parts) >= 2 {
				path := string(parts[1])
				if idx := strings.Index(path, "?"); idx != -1 {
					return path[:idx]
				}
				return path
			}
		}
	}
	return "/"
}
